export const SET_MATERIAL_LIST_OPTIONS = Symbol('SET_MATERIAL_LIST_OPTIONS')
export const SET_MATERIALS = Symbol('SET_MATERIALS')
export const SET_MATERIAL_TABLE_HEAD = Symbol('SET_MATERIAL_TABLE_HEAD')
export const SET_MATERIAL_TABLE_SELECTROWS = Symbol(
    'SET_MATERIAL_TABLE_SELECTROWS'
)
export const SET_MATERIAL_DETAIL = Symbol('SET_MATERIAL_DETAIL')
export const LOADING_MATERIAL_DETAIL = Symbol('LOADING_MATERIAL_DETAIL')
export const SET_MATERIAL_LIST_FILTER = Symbol('SET_MATERIAL_LIST_FILTER')

export const GET_MATERIAL_DETAIL_SAGA = Symbol('GET_MATERIAL_DETAIL_SAGA')
export const GET_MATERIALS_SAGA = Symbol('GET_MATERIALS_SAGA')
export const DELETE_MATERIAL_SAGA = Symbol('DELETE_MATERIAL_SAGA')
export const ADD_MATERIAL_SAGA = Symbol('ADD_MATERIAL_SAGA')
export const UPDATE_MATERIAL_SAGA = Symbol('UPDATE_MATERIAL_SAGA')
